# PersistentVolume for MySQL
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: "{{ .Release.Name }}-mysql-pv"
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/{{ .Values.storage.dataFolder }}/mysql"
#     type: DirectoryOrCreate
# ---
# PersistentVolumeClaim for MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-mysql-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# StatefulSet for MySQL
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-mysql"
spec:
  serviceName: "{{ .Release.Name }}-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-mysql"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-mysql"
    spec:
      imagePullSecrets:
        - name: generate-reg-cred
      initContainers:
        - name: "{{ .Release.Name }}-init-mysql"
          image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              if [ -z "$(ls -A /mnt/data)" ]; then
                cp -R /var/lib/mysql/* /mnt/data/
                chown -R mysql:mysql /mnt/data
              fi
          volumeMounts:
            - name: mysql-storage
              mountPath: /mnt/data
      containers:
        - name: "{{ .Release.Name }}-mysql"
          image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
          resources:
            # requests:
            #   cpu: "500m"
            #   memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.mysql.targetPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-mysql-pvc"
---
# Headless Service for MySQL
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mysql-svc"
spec:
  clusterIP: None
  selector:
    app: "{{ .Release.Name }}-mysql"
  ports:
    - port: {{ .Values.mysql.port }}
      name: "mysql"
      targetPort: {{ .Values.mysql.targetPort }}
