# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: "{{ .Release.Name }}-shared-pv"
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual  
#   hostPath:
#     path: "/data/{{ .Values.storage.dataFolder }}/files"
#     type: DirectoryOrCreate
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-shared-pvc"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: manual
  
